#!/bin/bash

# before running script do 
#                           export LD_LIBRARY_PATH=<pwd>:$LD_LIBRARY_PATH

gcc -fPIC -c mythread.c
gcc -shared -o libmythread.so mythread.o
gcc -L. main.c -o run -lmythread
rm mythread.o